/************************************************************************
APLIKACIJA	: Hotel Reservation - Diplomski rad
SKRIPTA		: 80_HOTEL_RES_Referent_Data_DML.sql
OPIS		: DML skripita za pocetne, referentne podatke
		
			
AUTOR		: M.Nikolic
VERZIJA     : 1.0.0
DATUM       : Nov 2024

ISTORIJA REVIZIJE
===============================================================================
REVIZIJA    |  	DATUM     	|  	OPIS IZMENA						  | POTPIS
-------------------------------------------------------------------------------
1.1.0			DEC-02-2024		Dodato novo stanje rezervacije		M.Nikolic
1.0.0   	 	NOV-20-2024   	Inicijalna verzija					M.Nikolic
********************************************************************************/
REM INSERTING into PLAYGROUND.E_LOV
SET DEFINE OFF;
Insert into PLAYGROUND.E_LOV (ID,KEY,VALUE,TYPE,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (61,'Gosti su došli','ARRIVED','RES_STATUS_MAPPING',to_date('11-OCT-2024 21:07:24','DD-MON-YYYY HH24:MI:SS'),'PLAYGROUND',to_date('11-OCT-2024 21:10:07','DD-MON-YYYY HH24:MI:SS'),'PLAYGROUND');
Insert into PLAYGROUND.E_LOV (ID,KEY,VALUE,TYPE,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (62,'Čekirano','CHECKED IN','RES_STATUS_MAPPING',to_date('11-OCT-2024 21:10:07','DD-MON-YYYY HH24:MI:SS'),'PLAYGROUND',to_date('11-OCT-2024 21:10:07','DD-MON-YYYY HH24:MI:SS'),'PLAYGROUND');
Insert into PLAYGROUND.E_LOV (ID,KEY,VALUE,TYPE,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (63,'Potvrđeno','CONFIRMED','RES_STATUS_MAPPING',to_date('11-OCT-2024 21:10:07','DD-MON-YYYY HH24:MI:SS'),'PLAYGROUND',to_date('11-OCT-2024 21:10:07','DD-MON-YYYY HH24:MI:SS'),'PLAYGROUND');
Insert into PLAYGROUND.E_LOV (ID,KEY,VALUE,TYPE,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (64,'Prijava otvorena','CHECK IN OPEN','RES_STATUS_MAPPING',to_date('11-OCT-2024 21:10:07','DD-MON-YYYY HH24:MI:SS'),'PLAYGROUND',to_date('11-OCT-2024 21:10:07','DD-MON-YYYY HH24:MI:SS'),'PLAYGROUND');
Insert into PLAYGROUND.E_LOV (ID,KEY,VALUE,TYPE,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (65,'Kreirana/Nova','CREATED','RES_STATUS_MAPPING',to_date('11-OCT-2024 21:10:07','DD-MON-YYYY HH24:MI:SS'),'PLAYGROUND',to_date('11-OCT-2024 21:10:07','DD-MON-YYYY HH24:MI:SS'),'PLAYGROUND');
Insert into PLAYGROUND.E_LOV (ID,KEY,VALUE,TYPE,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (122,'Otkazana','CANCELED','RES_STATUS_MAPPING',to_date('17-OCT-2024 13:27:14','DD-MON-YYYY HH24:MI:SS'),'PLAYGROUND',to_date('17-OCT-2024 13:29:07','DD-MON-YYYY HH24:MI:SS'),'PLAYGROUND');
Insert into PLAYGROUND.E_LOV (ID,KEY,VALUE,TYPE,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (141,'SEND_MAIL_FLG','Y','SYS_CONFIG',to_date('18-OCT-2024 00:00:00','DD-MON-YYYY HH24:MI:SS'),'PLAYGROUND',to_date('29-OCT-2024 11:01:09','DD-MON-YYYY HH24:MI:SS'),'MNIKOLIC');
Insert into PLAYGROUND.E_LOV (ID,KEY,VALUE,TYPE,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (1,'SMTP_PASS','<SMTP SIFRA>','SYS_CONFIG',to_date('04-OCT-2024 00:00:00','DD-MON-YYYY HH24:MI:SS'),'PLAYGROUND',to_date('14-OCT-2024 20:39:53','DD-MON-YYYY HH24:MI:SS'),'PLAYGROUND');
Insert into PLAYGROUND.E_LOV (ID,KEY,VALUE,TYPE,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (2,'BREAKFAST_PRICE_PER_PERSON','800','HOTEL_REF',to_date('04-OCT-2024 00:00:00','DD-MON-YYYY HH24:MI:SS'),'PLAYGROUND',to_date('14-OCT-2024 20:50:26','DD-MON-YYYY HH24:MI:SS'),'MNIKOLIC');
Insert into PLAYGROUND.E_LOV (ID,KEY,VALUE,TYPE,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (181,'0','46','DASH_HOTEL_UTIL',to_date('31-OCT-2024 00:00:00','DD-MON-YYYY HH24:MI:SS'),'PLAYGROUND',to_date('22-NOV-2024 12:23:39','DD-MON-YYYY HH24:MI:SS'),'PLAYGROUND');
Insert into PLAYGROUND.E_LOV (ID,KEY,VALUE,TYPE,CREATED,CREATED_BY,UPDATED,UPDATED_BY) values (201,'Nije se pojavio','NO SHOW','RES_STATUS_MAPPING',to_date('28-NOV-2024 10:13:36','DD-MON-YYYY HH24:MI:SS'),'PLAYGROUND',to_date('28-NOV-2024 10:13:36','DD-MON-YYYY HH24:MI:SS'),'PLAYGROUND');
